/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmcti.cmts.domain.model.impl;

import com.cmcti.cmts.domain.model.Cmts;
import com.cmcti.cmts.domain.model.CmtsModel;
import com.cmcti.cmts.domain.model.CmtsSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Cmts service. Represents a row in the &quot;CMTS_Cmts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cmcti.cmts.domain.model.CmtsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CmtsImpl}.
 * </p>
 *
 * @author richard
 * @see CmtsImpl
 * @see com.cmcti.cmts.domain.model.Cmts
 * @see com.cmcti.cmts.domain.model.CmtsModel
 * @generated
 */
@JSON(strict = true)
public class CmtsModelImpl extends BaseModelImpl<Cmts> implements CmtsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cmts model instance should use the {@link com.cmcti.cmts.domain.model.Cmts} interface instead.
	 */
	public static final String TABLE_NAME = "CMTS_Cmts";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cmtsId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "title", Types.VARCHAR },
			{ "host", Types.VARCHAR },
			{ "community", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "enable", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table CMTS_Cmts (cmtsId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,host VARCHAR(75) null,community VARCHAR(75) null,description VARCHAR(75) null,enable BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table CMTS_Cmts";
	public static final String ORDER_BY_JPQL = " ORDER BY cmts.cmtsId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMTS_Cmts.cmtsId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.cmcti.cmts.domain.model.Cmts"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.cmcti.cmts.domain.model.Cmts"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.cmcti.cmts.domain.model.Cmts"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static long CMTSID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Cmts toModel(CmtsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Cmts model = new CmtsImpl();

		model.setCmtsId(soapModel.getCmtsId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTitle(soapModel.getTitle());
		model.setHost(soapModel.getHost());
		model.setCommunity(soapModel.getCommunity());
		model.setDescription(soapModel.getDescription());
		model.setEnable(soapModel.getEnable());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Cmts> toModels(CmtsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Cmts> models = new ArrayList<Cmts>(soapModels.length);

		for (CmtsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.cmcti.cmts.domain.model.Cmts"));

	public CmtsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cmtsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCmtsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cmtsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Cmts.class;
	}

	@Override
	public String getModelClassName() {
		return Cmts.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cmtsId", getCmtsId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("title", getTitle());
		attributes.put("host", getHost());
		attributes.put("community", getCommunity());
		attributes.put("description", getDescription());
		attributes.put("enable", getEnable());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cmtsId = (Long)attributes.get("cmtsId");

		if (cmtsId != null) {
			setCmtsId(cmtsId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String host = (String)attributes.get("host");

		if (host != null) {
			setHost(host);
		}

		String community = (String)attributes.get("community");

		if (community != null) {
			setCommunity(community);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Boolean enable = (Boolean)attributes.get("enable");

		if (enable != null) {
			setEnable(enable);
		}
	}

	@JSON
	@Override
	public long getCmtsId() {
		return _cmtsId;
	}

	@Override
	public void setCmtsId(long cmtsId) {
		_cmtsId = cmtsId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getHost() {
		if (_host == null) {
			return StringPool.BLANK;
		}
		else {
			return _host;
		}
	}

	@Override
	public void setHost(String host) {
		_host = host;
	}

	@JSON
	@Override
	public String getCommunity() {
		if (_community == null) {
			return StringPool.BLANK;
		}
		else {
			return _community;
		}
	}

	@Override
	public void setCommunity(String community) {
		_community = community;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public boolean getEnable() {
		return _enable;
	}

	@Override
	public boolean isEnable() {
		return _enable;
	}

	@Override
	public void setEnable(boolean enable) {
		_enable = enable;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Cmts.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Cmts toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Cmts)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CmtsImpl cmtsImpl = new CmtsImpl();

		cmtsImpl.setCmtsId(getCmtsId());
		cmtsImpl.setGroupId(getGroupId());
		cmtsImpl.setCompanyId(getCompanyId());
		cmtsImpl.setUserId(getUserId());
		cmtsImpl.setUserName(getUserName());
		cmtsImpl.setCreateDate(getCreateDate());
		cmtsImpl.setModifiedDate(getModifiedDate());
		cmtsImpl.setTitle(getTitle());
		cmtsImpl.setHost(getHost());
		cmtsImpl.setCommunity(getCommunity());
		cmtsImpl.setDescription(getDescription());
		cmtsImpl.setEnable(getEnable());

		cmtsImpl.resetOriginalValues();

		return cmtsImpl;
	}

	@Override
	public int compareTo(Cmts cmts) {
		long primaryKey = cmts.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Cmts)) {
			return false;
		}

		Cmts cmts = (Cmts)obj;

		long primaryKey = cmts.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CmtsModelImpl cmtsModelImpl = this;

		cmtsModelImpl._originalUserId = cmtsModelImpl._userId;

		cmtsModelImpl._setOriginalUserId = false;

		cmtsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Cmts> toCacheModel() {
		CmtsCacheModel cmtsCacheModel = new CmtsCacheModel();

		cmtsCacheModel.cmtsId = getCmtsId();

		cmtsCacheModel.groupId = getGroupId();

		cmtsCacheModel.companyId = getCompanyId();

		cmtsCacheModel.userId = getUserId();

		cmtsCacheModel.userName = getUserName();

		String userName = cmtsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cmtsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cmtsCacheModel.createDate = createDate.getTime();
		}
		else {
			cmtsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cmtsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cmtsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cmtsCacheModel.title = getTitle();

		String title = cmtsCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			cmtsCacheModel.title = null;
		}

		cmtsCacheModel.host = getHost();

		String host = cmtsCacheModel.host;

		if ((host != null) && (host.length() == 0)) {
			cmtsCacheModel.host = null;
		}

		cmtsCacheModel.community = getCommunity();

		String community = cmtsCacheModel.community;

		if ((community != null) && (community.length() == 0)) {
			cmtsCacheModel.community = null;
		}

		cmtsCacheModel.description = getDescription();

		String description = cmtsCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			cmtsCacheModel.description = null;
		}

		cmtsCacheModel.enable = getEnable();

		return cmtsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{cmtsId=");
		sb.append(getCmtsId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", host=");
		sb.append(getHost());
		sb.append(", community=");
		sb.append(getCommunity());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", enable=");
		sb.append(getEnable());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.cmcti.cmts.domain.model.Cmts");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cmtsId</column-name><column-value><![CDATA[");
		sb.append(getCmtsId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>host</column-name><column-value><![CDATA[");
		sb.append(getHost());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>community</column-name><column-value><![CDATA[");
		sb.append(getCommunity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enable</column-name><column-value><![CDATA[");
		sb.append(getEnable());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Cmts.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Cmts.class };
	private long _cmtsId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _title;
	private String _host;
	private String _community;
	private String _description;
	private boolean _enable;
	private long _columnBitmask;
	private Cmts _escapedModel;
}