/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmcti.cmts.domain.model.impl;

import com.cmcti.cmts.domain.model.CustomerMacMapping;
import com.cmcti.cmts.domain.model.CustomerMacMappingModel;
import com.cmcti.cmts.domain.model.CustomerMacMappingSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CustomerMacMapping service. Represents a row in the &quot;CMTS_MONITOR_CustomerMacMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cmcti.cmts.domain.model.CustomerMacMappingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomerMacMappingImpl}.
 * </p>
 *
 * @author richard
 * @see CustomerMacMappingImpl
 * @see com.cmcti.cmts.domain.model.CustomerMacMapping
 * @see com.cmcti.cmts.domain.model.CustomerMacMappingModel
 * @generated
 */
@JSON(strict = true)
public class CustomerMacMappingModelImpl extends BaseModelImpl<CustomerMacMapping>
	implements CustomerMacMappingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a customer mac mapping model instance should use the {@link com.cmcti.cmts.domain.model.CustomerMacMapping} interface instead.
	 */
	public static final String TABLE_NAME = "CMTS_MONITOR_CustomerMacMapping";
	public static final Object[][] TABLE_COLUMNS = {
			{ "customerMacId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "title", Types.VARCHAR },
			{ "macAddress", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMTS_MONITOR_CustomerMacMapping (customerMacId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,macAddress VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMTS_MONITOR_CustomerMacMapping";
	public static final String ORDER_BY_JPQL = " ORDER BY customerMacMapping.title ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMTS_MONITOR_CustomerMacMapping.title ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.cmcti.cmts.domain.model.CustomerMacMapping"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.cmcti.cmts.domain.model.CustomerMacMapping"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.cmcti.cmts.domain.model.CustomerMacMapping"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static long TITLE_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CustomerMacMapping toModel(CustomerMacMappingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CustomerMacMapping model = new CustomerMacMappingImpl();

		model.setCustomerMacId(soapModel.getCustomerMacId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTitle(soapModel.getTitle());
		model.setMacAddress(soapModel.getMacAddress());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CustomerMacMapping> toModels(
		CustomerMacMappingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CustomerMacMapping> models = new ArrayList<CustomerMacMapping>(soapModels.length);

		for (CustomerMacMappingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.cmcti.cmts.domain.model.CustomerMacMapping"));

	public CustomerMacMappingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _customerMacId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCustomerMacId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _customerMacId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CustomerMacMapping.class;
	}

	@Override
	public String getModelClassName() {
		return CustomerMacMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("customerMacId", getCustomerMacId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("title", getTitle());
		attributes.put("macAddress", getMacAddress());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long customerMacId = (Long)attributes.get("customerMacId");

		if (customerMacId != null) {
			setCustomerMacId(customerMacId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String macAddress = (String)attributes.get("macAddress");

		if (macAddress != null) {
			setMacAddress(macAddress);
		}
	}

	@JSON
	@Override
	public long getCustomerMacId() {
		return _customerMacId;
	}

	@Override
	public void setCustomerMacId(long customerMacId) {
		_customerMacId = customerMacId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask = -1L;

		_title = title;
	}

	@JSON
	@Override
	public String getMacAddress() {
		if (_macAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _macAddress;
		}
	}

	@Override
	public void setMacAddress(String macAddress) {
		_macAddress = macAddress;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CustomerMacMapping.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CustomerMacMapping toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CustomerMacMapping)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CustomerMacMappingImpl customerMacMappingImpl = new CustomerMacMappingImpl();

		customerMacMappingImpl.setCustomerMacId(getCustomerMacId());
		customerMacMappingImpl.setGroupId(getGroupId());
		customerMacMappingImpl.setCompanyId(getCompanyId());
		customerMacMappingImpl.setUserId(getUserId());
		customerMacMappingImpl.setCreateDate(getCreateDate());
		customerMacMappingImpl.setModifiedDate(getModifiedDate());
		customerMacMappingImpl.setTitle(getTitle());
		customerMacMappingImpl.setMacAddress(getMacAddress());

		customerMacMappingImpl.resetOriginalValues();

		return customerMacMappingImpl;
	}

	@Override
	public int compareTo(CustomerMacMapping customerMacMapping) {
		int value = 0;

		value = getTitle().compareTo(customerMacMapping.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CustomerMacMapping)) {
			return false;
		}

		CustomerMacMapping customerMacMapping = (CustomerMacMapping)obj;

		long primaryKey = customerMacMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CustomerMacMappingModelImpl customerMacMappingModelImpl = this;

		customerMacMappingModelImpl._originalUserId = customerMacMappingModelImpl._userId;

		customerMacMappingModelImpl._setOriginalUserId = false;

		customerMacMappingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CustomerMacMapping> toCacheModel() {
		CustomerMacMappingCacheModel customerMacMappingCacheModel = new CustomerMacMappingCacheModel();

		customerMacMappingCacheModel.customerMacId = getCustomerMacId();

		customerMacMappingCacheModel.groupId = getGroupId();

		customerMacMappingCacheModel.companyId = getCompanyId();

		customerMacMappingCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			customerMacMappingCacheModel.createDate = createDate.getTime();
		}
		else {
			customerMacMappingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			customerMacMappingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			customerMacMappingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		customerMacMappingCacheModel.title = getTitle();

		String title = customerMacMappingCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			customerMacMappingCacheModel.title = null;
		}

		customerMacMappingCacheModel.macAddress = getMacAddress();

		String macAddress = customerMacMappingCacheModel.macAddress;

		if ((macAddress != null) && (macAddress.length() == 0)) {
			customerMacMappingCacheModel.macAddress = null;
		}

		return customerMacMappingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{customerMacId=");
		sb.append(getCustomerMacId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", macAddress=");
		sb.append(getMacAddress());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.cmcti.cmts.domain.model.CustomerMacMapping");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>customerMacId</column-name><column-value><![CDATA[");
		sb.append(getCustomerMacId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>macAddress</column-name><column-value><![CDATA[");
		sb.append(getMacAddress());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CustomerMacMapping.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CustomerMacMapping.class
		};
	private long _customerMacId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createDate;
	private Date _modifiedDate;
	private String _title;
	private String _macAddress;
	private long _columnBitmask;
	private CustomerMacMapping _escapedModel;
}