/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmcti.cmts.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CableModem service. Represents a row in the &quot;CMTS_CableModem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmcti.cmts.domain.model.impl.CableModemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmcti.cmts.domain.model.impl.CableModemImpl}.
 * </p>
 *
 * @author richard
 * @see CableModem
 * @see com.cmcti.cmts.domain.model.impl.CableModemImpl
 * @see com.cmcti.cmts.domain.model.impl.CableModemModelImpl
 * @generated
 */
public interface CableModemModel extends BaseModel<CableModem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cable modem model instance should use the {@link CableModem} interface instead.
	 */

	/**
	 * Returns the primary key of this cable modem.
	 *
	 * @return the primary key of this cable modem
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this cable modem.
	 *
	 * @param primaryKey the primary key of this cable modem
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the mac address of this cable modem.
	 *
	 * @return the mac address of this cable modem
	 */
	@AutoEscape
	public String getMacAddress();

	/**
	 * Sets the mac address of this cable modem.
	 *
	 * @param macAddress the mac address of this cable modem
	 */
	public void setMacAddress(String macAddress);

	/**
	 * Returns the create date of this cable modem.
	 *
	 * @return the create date of this cable modem
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cable modem.
	 *
	 * @param createDate the create date of this cable modem
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cable modem.
	 *
	 * @return the modified date of this cable modem
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cable modem.
	 *
	 * @param modifiedDate the modified date of this cable modem
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fec uncorrectable of this cable modem.
	 *
	 * @return the fec uncorrectable of this cable modem
	 */
	public double getFecUncorrectable();

	/**
	 * Sets the fec uncorrectable of this cable modem.
	 *
	 * @param fecUncorrectable the fec uncorrectable of this cable modem
	 */
	public void setFecUncorrectable(double fecUncorrectable);

	/**
	 * Returns the fec corrected of this cable modem.
	 *
	 * @return the fec corrected of this cable modem
	 */
	public double getFecCorrected();

	/**
	 * Sets the fec corrected of this cable modem.
	 *
	 * @param fecCorrected the fec corrected of this cable modem
	 */
	public void setFecCorrected(double fecCorrected);

	/**
	 * Returns the micro ref of this cable modem.
	 *
	 * @return the micro ref of this cable modem
	 */
	public long getMicroRef();

	/**
	 * Sets the micro ref of this cable modem.
	 *
	 * @param microRef the micro ref of this cable modem
	 */
	public void setMicroRef(long microRef);

	/**
	 * Returns the rx power of this cable modem.
	 *
	 * @return the rx power of this cable modem
	 */
	public int getRxPower();

	/**
	 * Sets the rx power of this cable modem.
	 *
	 * @param rxPower the rx power of this cable modem
	 */
	public void setRxPower(int rxPower);

	/**
	 * Returns the tx power of this cable modem.
	 *
	 * @return the tx power of this cable modem
	 */
	public int getTxPower();

	/**
	 * Sets the tx power of this cable modem.
	 *
	 * @param txPower the tx power of this cable modem
	 */
	public void setTxPower(int txPower);

	/**
	 * Returns the us power of this cable modem.
	 *
	 * @return the us power of this cable modem
	 */
	public int getUsPower();

	/**
	 * Sets the us power of this cable modem.
	 *
	 * @param usPower the us power of this cable modem
	 */
	public void setUsPower(int usPower);

	/**
	 * Returns the ds power of this cable modem.
	 *
	 * @return the ds power of this cable modem
	 */
	public int getDsPower();

	/**
	 * Sets the ds power of this cable modem.
	 *
	 * @param dsPower the ds power of this cable modem
	 */
	public void setDsPower(int dsPower);

	/**
	 * Returns the uncorrectables of this cable modem.
	 *
	 * @return the uncorrectables of this cable modem
	 */
	public long getUncorrectables();

	/**
	 * Sets the uncorrectables of this cable modem.
	 *
	 * @param uncorrectables the uncorrectables of this cable modem
	 */
	public void setUncorrectables(long uncorrectables);

	/**
	 * Returns the correcteds of this cable modem.
	 *
	 * @return the correcteds of this cable modem
	 */
	public long getCorrecteds();

	/**
	 * Sets the correcteds of this cable modem.
	 *
	 * @param correcteds the correcteds of this cable modem
	 */
	public void setCorrecteds(long correcteds);

	/**
	 * Returns the unerroreds of this cable modem.
	 *
	 * @return the unerroreds of this cable modem
	 */
	public long getUnerroreds();

	/**
	 * Sets the unerroreds of this cable modem.
	 *
	 * @param unerroreds the unerroreds of this cable modem
	 */
	public void setUnerroreds(long unerroreds);

	/**
	 * Returns the ds s n r of this cable modem.
	 *
	 * @return the ds s n r of this cable modem
	 */
	public int getDsSNR();

	/**
	 * Sets the ds s n r of this cable modem.
	 *
	 * @param dsSNR the ds s n r of this cable modem
	 */
	public void setDsSNR(int dsSNR);

	/**
	 * Returns the us s n r of this cable modem.
	 *
	 * @return the us s n r of this cable modem
	 */
	public int getUsSNR();

	/**
	 * Sets the us s n r of this cable modem.
	 *
	 * @param usSNR the us s n r of this cable modem
	 */
	public void setUsSNR(int usSNR);

	/**
	 * Returns the uc if index of this cable modem.
	 *
	 * @return the uc if index of this cable modem
	 */
	public int getUcIfIndex();

	/**
	 * Sets the uc if index of this cable modem.
	 *
	 * @param ucIfIndex the uc if index of this cable modem
	 */
	public void setUcIfIndex(int ucIfIndex);

	/**
	 * Returns the dc if index of this cable modem.
	 *
	 * @return the dc if index of this cable modem
	 */
	public int getDcIfIndex();

	/**
	 * Sets the dc if index of this cable modem.
	 *
	 * @param dcIfIndex the dc if index of this cable modem
	 */
	public void setDcIfIndex(int dcIfIndex);

	/**
	 * Returns the cm sub index of this cable modem.
	 *
	 * @return the cm sub index of this cable modem
	 */
	@AutoEscape
	public String getCmSubIndex();

	/**
	 * Sets the cm sub index of this cable modem.
	 *
	 * @param cmSubIndex the cm sub index of this cable modem
	 */
	public void setCmSubIndex(String cmSubIndex);

	/**
	 * Returns the cmts ID of this cable modem.
	 *
	 * @return the cmts ID of this cable modem
	 */
	public long getCmtsId();

	/**
	 * Sets the cmts ID of this cable modem.
	 *
	 * @param cmtsId the cmts ID of this cable modem
	 */
	public void setCmtsId(long cmtsId);

	/**
	 * Returns the cm index of this cable modem.
	 *
	 * @return the cm index of this cable modem
	 */
	public int getCmIndex();

	/**
	 * Sets the cm index of this cable modem.
	 *
	 * @param cmIndex the cm index of this cable modem
	 */
	public void setCmIndex(int cmIndex);

	/**
	 * Returns the status of this cable modem.
	 *
	 * @return the status of this cable modem
	 */
	public int getStatus();

	/**
	 * Sets the status of this cable modem.
	 *
	 * @param status the status of this cable modem
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CableModem cableModem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CableModem> toCacheModel();

	@Override
	public CableModem toEscapedModel();

	@Override
	public CableModem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}