/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmcti.cmts.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CustomerMacMapping service. Represents a row in the &quot;CustomerMacMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmcti.cmts.domain.model.impl.CustomerMacMappingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmcti.cmts.domain.model.impl.CustomerMacMappingImpl}.
 * </p>
 *
 * @author richard
 * @see CustomerMacMapping
 * @see com.cmcti.cmts.domain.model.impl.CustomerMacMappingImpl
 * @see com.cmcti.cmts.domain.model.impl.CustomerMacMappingModelImpl
 * @generated
 */
public interface CustomerMacMappingModel extends BaseModel<CustomerMacMapping> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer mac mapping model instance should use the {@link CustomerMacMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this customer mac mapping.
	 *
	 * @return the primary key of this customer mac mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer mac mapping.
	 *
	 * @param primaryKey the primary key of this customer mac mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the customer mac ID of this customer mac mapping.
	 *
	 * @return the customer mac ID of this customer mac mapping
	 */
	public long getCustomerMacId();

	/**
	 * Sets the customer mac ID of this customer mac mapping.
	 *
	 * @param customerMacId the customer mac ID of this customer mac mapping
	 */
	public void setCustomerMacId(long customerMacId);

	/**
	 * Returns the group ID of this customer mac mapping.
	 *
	 * @return the group ID of this customer mac mapping
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this customer mac mapping.
	 *
	 * @param groupId the group ID of this customer mac mapping
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this customer mac mapping.
	 *
	 * @return the company ID of this customer mac mapping
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this customer mac mapping.
	 *
	 * @param companyId the company ID of this customer mac mapping
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this customer mac mapping.
	 *
	 * @return the user ID of this customer mac mapping
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this customer mac mapping.
	 *
	 * @param userId the user ID of this customer mac mapping
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this customer mac mapping.
	 *
	 * @return the user uuid of this customer mac mapping
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this customer mac mapping.
	 *
	 * @param userUuid the user uuid of this customer mac mapping
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this customer mac mapping.
	 *
	 * @return the create date of this customer mac mapping
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this customer mac mapping.
	 *
	 * @param createDate the create date of this customer mac mapping
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this customer mac mapping.
	 *
	 * @return the modified date of this customer mac mapping
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this customer mac mapping.
	 *
	 * @param modifiedDate the modified date of this customer mac mapping
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this customer mac mapping.
	 *
	 * @return the title of this customer mac mapping
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this customer mac mapping.
	 *
	 * @param title the title of this customer mac mapping
	 */
	public void setTitle(String title);

	/**
	 * Returns the mac address of this customer mac mapping.
	 *
	 * @return the mac address of this customer mac mapping
	 */
	@AutoEscape
	public String getMacAddress();

	/**
	 * Sets the mac address of this customer mac mapping.
	 *
	 * @param macAddress the mac address of this customer mac mapping
	 */
	public void setMacAddress(String macAddress);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CustomerMacMapping customerMacMapping);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CustomerMacMapping> toCacheModel();

	@Override
	public CustomerMacMapping toEscapedModel();

	@Override
	public CustomerMacMapping toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}