/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmcti.cmts.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MerchantScope service. Represents a row in the &quot;CMTS_MerchantScope&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmcti.cmts.domain.model.impl.MerchantScopeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmcti.cmts.domain.model.impl.MerchantScopeImpl}.
 * </p>
 *
 * @author richard
 * @see MerchantScope
 * @see com.cmcti.cmts.domain.model.impl.MerchantScopeImpl
 * @see com.cmcti.cmts.domain.model.impl.MerchantScopeModelImpl
 * @generated
 */
public interface MerchantScopeModel extends BaseModel<MerchantScope>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a merchant scope model instance should use the {@link MerchantScope} interface instead.
	 */

	/**
	 * Returns the primary key of this merchant scope.
	 *
	 * @return the primary key of this merchant scope
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this merchant scope.
	 *
	 * @param primaryKey the primary key of this merchant scope
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the merchant scope ID of this merchant scope.
	 *
	 * @return the merchant scope ID of this merchant scope
	 */
	public long getMerchantScopeId();

	/**
	 * Sets the merchant scope ID of this merchant scope.
	 *
	 * @param merchantScopeId the merchant scope ID of this merchant scope
	 */
	public void setMerchantScopeId(long merchantScopeId);

	/**
	 * Returns the group ID of this merchant scope.
	 *
	 * @return the group ID of this merchant scope
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this merchant scope.
	 *
	 * @param groupId the group ID of this merchant scope
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this merchant scope.
	 *
	 * @return the company ID of this merchant scope
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this merchant scope.
	 *
	 * @param companyId the company ID of this merchant scope
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this merchant scope.
	 *
	 * @return the user ID of this merchant scope
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this merchant scope.
	 *
	 * @param userId the user ID of this merchant scope
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this merchant scope.
	 *
	 * @return the user uuid of this merchant scope
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this merchant scope.
	 *
	 * @param userUuid the user uuid of this merchant scope
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this merchant scope.
	 *
	 * @return the user name of this merchant scope
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this merchant scope.
	 *
	 * @param userName the user name of this merchant scope
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this merchant scope.
	 *
	 * @return the create date of this merchant scope
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this merchant scope.
	 *
	 * @param createDate the create date of this merchant scope
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this merchant scope.
	 *
	 * @return the modified date of this merchant scope
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this merchant scope.
	 *
	 * @param modifiedDate the modified date of this merchant scope
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the cmts ID of this merchant scope.
	 *
	 * @return the cmts ID of this merchant scope
	 */
	public long getCmtsId();

	/**
	 * Sets the cmts ID of this merchant scope.
	 *
	 * @param cmtsId the cmts ID of this merchant scope
	 */
	public void setCmtsId(long cmtsId);

	/**
	 * Returns the if index of this merchant scope.
	 *
	 * @return the if index of this merchant scope
	 */
	public int getIfIndex();

	/**
	 * Sets the if index of this merchant scope.
	 *
	 * @param ifIndex the if index of this merchant scope
	 */
	public void setIfIndex(int ifIndex);

	/**
	 * Returns the merchant code of this merchant scope.
	 *
	 * @return the merchant code of this merchant scope
	 */
	@AutoEscape
	public String getMerchantCode();

	/**
	 * Sets the merchant code of this merchant scope.
	 *
	 * @param merchantCode the merchant code of this merchant scope
	 */
	public void setMerchantCode(String merchantCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MerchantScope merchantScope);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MerchantScope> toCacheModel();

	@Override
	public MerchantScope toEscapedModel();

	@Override
	public MerchantScope toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}