/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmcti.cmts.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Merchant service. Represents a row in the &quot;CMTS_Merchant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmcti.cmts.domain.model.impl.MerchantModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmcti.cmts.domain.model.impl.MerchantImpl}.
 * </p>
 *
 * @author richard
 * @see Merchant
 * @see com.cmcti.cmts.domain.model.impl.MerchantImpl
 * @see com.cmcti.cmts.domain.model.impl.MerchantModelImpl
 * @generated
 */
public interface MerchantModel extends BaseModel<Merchant>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a merchant model instance should use the {@link Merchant} interface instead.
	 */

	/**
	 * Returns the primary key of this merchant.
	 *
	 * @return the primary key of this merchant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this merchant.
	 *
	 * @param primaryKey the primary key of this merchant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the merchant ID of this merchant.
	 *
	 * @return the merchant ID of this merchant
	 */
	public long getMerchantId();

	/**
	 * Sets the merchant ID of this merchant.
	 *
	 * @param merchantId the merchant ID of this merchant
	 */
	public void setMerchantId(long merchantId);

	/**
	 * Returns the group ID of this merchant.
	 *
	 * @return the group ID of this merchant
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this merchant.
	 *
	 * @param groupId the group ID of this merchant
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this merchant.
	 *
	 * @return the company ID of this merchant
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this merchant.
	 *
	 * @param companyId the company ID of this merchant
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this merchant.
	 *
	 * @return the user ID of this merchant
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this merchant.
	 *
	 * @param userId the user ID of this merchant
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this merchant.
	 *
	 * @return the user uuid of this merchant
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this merchant.
	 *
	 * @param userUuid the user uuid of this merchant
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this merchant.
	 *
	 * @return the user name of this merchant
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this merchant.
	 *
	 * @param userName the user name of this merchant
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this merchant.
	 *
	 * @return the create date of this merchant
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this merchant.
	 *
	 * @param createDate the create date of this merchant
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this merchant.
	 *
	 * @return the modified date of this merchant
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this merchant.
	 *
	 * @param modifiedDate the modified date of this merchant
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this merchant.
	 *
	 * @return the title of this merchant
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this merchant.
	 *
	 * @param title the title of this merchant
	 */
	public void setTitle(String title);

	/**
	 * Returns the code of this merchant.
	 *
	 * @return the code of this merchant
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this merchant.
	 *
	 * @param code the code of this merchant
	 */
	public void setCode(String code);

	/**
	 * Returns the parent ID of this merchant.
	 *
	 * @return the parent ID of this merchant
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this merchant.
	 *
	 * @param parentId the parent ID of this merchant
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the parent code of this merchant.
	 *
	 * @return the parent code of this merchant
	 */
	@AutoEscape
	public String getParentCode();

	/**
	 * Sets the parent code of this merchant.
	 *
	 * @param parentCode the parent code of this merchant
	 */
	public void setParentCode(String parentCode);

	/**
	 * Returns the description of this merchant.
	 *
	 * @return the description of this merchant
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this merchant.
	 *
	 * @param description the description of this merchant
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Merchant merchant);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Merchant> toCacheModel();

	@Override
	public Merchant toEscapedModel();

	@Override
	public Merchant toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}