/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmcti.cmts.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Option service. Represents a row in the &quot;CMTS_Option&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmcti.cmts.domain.model.impl.OptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmcti.cmts.domain.model.impl.OptionImpl}.
 * </p>
 *
 * @author richard
 * @see Option
 * @see com.cmcti.cmts.domain.model.impl.OptionImpl
 * @see com.cmcti.cmts.domain.model.impl.OptionModelImpl
 * @generated
 */
public interface OptionModel extends BaseModel<Option>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a option model instance should use the {@link Option} interface instead.
	 */

	/**
	 * Returns the primary key of this option.
	 *
	 * @return the primary key of this option
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this option.
	 *
	 * @param primaryKey the primary key of this option
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the option ID of this option.
	 *
	 * @return the option ID of this option
	 */
	public long getOptionId();

	/**
	 * Sets the option ID of this option.
	 *
	 * @param optionId the option ID of this option
	 */
	public void setOptionId(long optionId);

	/**
	 * Returns the group ID of this option.
	 *
	 * @return the group ID of this option
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this option.
	 *
	 * @param groupId the group ID of this option
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this option.
	 *
	 * @return the company ID of this option
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this option.
	 *
	 * @param companyId the company ID of this option
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this option.
	 *
	 * @return the user ID of this option
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this option.
	 *
	 * @param userId the user ID of this option
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this option.
	 *
	 * @return the user uuid of this option
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this option.
	 *
	 * @param userUuid the user uuid of this option
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this option.
	 *
	 * @return the user name of this option
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this option.
	 *
	 * @param userName the user name of this option
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this option.
	 *
	 * @return the create date of this option
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this option.
	 *
	 * @param createDate the create date of this option
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this option.
	 *
	 * @return the modified date of this option
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this option.
	 *
	 * @param modifiedDate the modified date of this option
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the option type of this option.
	 *
	 * @return the option type of this option
	 */
	@AutoEscape
	public String getOptionType();

	/**
	 * Sets the option type of this option.
	 *
	 * @param optionType the option type of this option
	 */
	public void setOptionType(String optionType);

	/**
	 * Returns the option key of this option.
	 *
	 * @return the option key of this option
	 */
	@AutoEscape
	public String getOptionKey();

	/**
	 * Sets the option key of this option.
	 *
	 * @param optionKey the option key of this option
	 */
	public void setOptionKey(String optionKey);

	/**
	 * Returns the option value of this option.
	 *
	 * @return the option value of this option
	 */
	@AutoEscape
	public String getOptionValue();

	/**
	 * Sets the option value of this option.
	 *
	 * @param optionValue the option value of this option
	 */
	public void setOptionValue(String optionValue);

	/**
	 * Returns the description of this option.
	 *
	 * @return the description of this option
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this option.
	 *
	 * @param description the description of this option
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Option option);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Option> toCacheModel();

	@Override
	public Option toEscapedModel();

	@Override
	public Option toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}