/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmcti.cmts.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UpChannelMetadata service. Represents a row in the &quot;CMTS_UpChannelMetadata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmcti.cmts.domain.model.impl.UpChannelMetadataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmcti.cmts.domain.model.impl.UpChannelMetadataImpl}.
 * </p>
 *
 * @author richard
 * @see UpChannelMetadata
 * @see com.cmcti.cmts.domain.model.impl.UpChannelMetadataImpl
 * @see com.cmcti.cmts.domain.model.impl.UpChannelMetadataModelImpl
 * @generated
 */
public interface UpChannelMetadataModel extends BaseModel<UpChannelMetadata> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a up channel metadata model instance should use the {@link UpChannelMetadata} interface instead.
	 */

	/**
	 * Returns the primary key of this up channel metadata.
	 *
	 * @return the primary key of this up channel metadata
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this up channel metadata.
	 *
	 * @param primaryKey the primary key of this up channel metadata
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the meta ID of this up channel metadata.
	 *
	 * @return the meta ID of this up channel metadata
	 */
	public long getMetaId();

	/**
	 * Sets the meta ID of this up channel metadata.
	 *
	 * @param metaId the meta ID of this up channel metadata
	 */
	public void setMetaId(long metaId);

	/**
	 * Returns the cmts ID of this up channel metadata.
	 *
	 * @return the cmts ID of this up channel metadata
	 */
	public long getCmtsId();

	/**
	 * Sets the cmts ID of this up channel metadata.
	 *
	 * @param cmtsId the cmts ID of this up channel metadata
	 */
	public void setCmtsId(long cmtsId);

	/**
	 * Returns the if index of this up channel metadata.
	 *
	 * @return the if index of this up channel metadata
	 */
	public int getIfIndex();

	/**
	 * Sets the if index of this up channel metadata.
	 *
	 * @param ifIndex the if index of this up channel metadata
	 */
	public void setIfIndex(int ifIndex);

	/**
	 * Returns the ds frequency of this up channel metadata.
	 *
	 * @return the ds frequency of this up channel metadata
	 */
	@AutoEscape
	public String getDsFrequency();

	/**
	 * Sets the ds frequency of this up channel metadata.
	 *
	 * @param dsFrequency the ds frequency of this up channel metadata
	 */
	public void setDsFrequency(String dsFrequency);

	/**
	 * Returns the ds qam of this up channel metadata.
	 *
	 * @return the ds qam of this up channel metadata
	 */
	@AutoEscape
	public String getDsQam();

	/**
	 * Sets the ds qam of this up channel metadata.
	 *
	 * @param dsQam the ds qam of this up channel metadata
	 */
	public void setDsQam(String dsQam);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UpChannelMetadata upChannelMetadata);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UpChannelMetadata> toCacheModel();

	@Override
	public UpChannelMetadata toEscapedModel();

	@Override
	public UpChannelMetadata toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}